### ISSUE TITLE
Replace rem usage with em

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#126]
* Can we find/create a font-size simulator for storybook?
* Why pixels in button, inputs... ?
* What about 3px instead of 0.2rem for focus-rings?
* What about px for border-radius?

**Comment by hsablonniere** [comment]
Maybe we should reconsider rem for em.
If the user has a `html { font-size: 15px }` we're a bit forked :cry: (it happens a lot)

**Comment by nhoizey** [comment]
I would love to have a "font-size simulator for storybook"!

**Comment by hsablonniere** [comment]
As you can see in #260, we started implementing this in the pricing components.

**Comment by hsablonniere** [comment]
TODO:

* [ ] write an ADR about this
