### ISSUE TITLE
Audit focus rings

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#128]
We have focus rings in lots of places:

* we should always reuse the same CSS for this
* we should also check if we can apply the transition everywhere

Audit consitency with:

* color
* width
* transition

https://adhoc.team/2022/02/08/creating-focus-style-for-themable-design-system/?utm_source=swlinks-tw

**Comment by florian-sanders-cc** [comment]
Now that Firefox has fixed the border-radius for outline ([see Firefox Issue](https://bugzilla.mozilla.org/show_bug.cgi?id=315209)), we can rely on outline to provide focus visibility instead (or in combination with box-shadow)

**Comment by florian-sanders-cc** [comment]
Already handled in the #281 issue
