### ISSUE TITLE
Add-on options

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-components#140]
Our add-ons will have more and more options over time. Currently, we did the `<cc-elasticsearch-options>` component to handle Elastic Stack options. We now have the `encrypt at rest` option that will be available for other add-ons like PostgreSQL, MySQL, MongoDB, ...

The idea is to have the options system for add-ons a bit more decoupled. Here are the components will we create, from bottom to top:

## `<cc-addon-option>`

`<cc-addon-option>` will be the container of the option. It will have:
- 2 attributes / properties: `title` and `logo`. Title is the option's name, logo is its logo.
- A default slot which will have the "description" of the option.
- Emit an event when the enable/disable toggle is hit.

## `<cc-addon-option-form>`

`<cc-addon-option-form>` will be the container of the possible multiple `<cc-addon-option>`. It will have:
- 2 attributes / properties: `title`, `options`. Title is the title of the add-on options. Currently for elastic it's `Options for the Elastic Stack`. Options is an array of options, see below. The component will iterate over this options array and pass the properties to the `<cc-addon-option>` components.
- Emit an event when the `confirm options` button is hit with the options states (enabled / disabled)

## `<cc-addon-elasticsearch-options>, <cc-addon-postgresql-options>, <cc-addon-mysql-options>, <cc-addon-mongodb-options>`

Those components will be the global components to display those options. They have the `i18n` for each add-on and instantiate a `<cc-addon-option-form>` with the correct properties. It will have:
- 1 attribute / property: `options`. Options is an array of the available options for this add-on. See below for the format.

### Options

It will be an array of objects where each object has:
- A logo (String). e.g: APM Logo
- A title (String). e.g: APM
- description (DOM): a Lit Element dom element with the option's description
- name (String): Internal to the `<cc-addon-option-form>` to identify the option's event.

**Comment by hsablonniere** [comment]
Reading this again, I wonder if we should/could remove the `-addon` for the ES, PG, MS and mongo components.

**Comment by BlackYoup** [comment]
I don't think we should drop it. If we ever need another specific component for those add-ons, it would be weird to have `<cc-addon-postgresql>` and `<cc-addon-postgresql-whatever>`. When we will have to redo all the add-ons dashboard, we might need such component.

**Comment by BlackYoup** [comment]
I'm closing this one for now, I'll open a new issue for the encryption option for some of the add-ons.
