### ISSUE TITLE
Implement cc-pricing-table

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#196]
A component that displays "items" with features and pricies in a table (or compact list when narrow).

TODO:

* [x] Add a story to show an example with a runtime (ex: Ruby)
* [x] Change the API for `price` on an `item` from `number` to `{ monthly: number, daily: number }`
* [x] Fix alignement in narrow mode
* [x] Change `_onChangeDataState()` function to not modify the DOM ourselves 
* [x] Think about how we could handle alignement of header (feature names)
* [x] Think about how and when we decide the array is not wide enough
* [x] Update docs
* [x] Fix i18n (plan)
* [x] plus and toggle btn => use new circle cc-button with image
  * [x] Cleanup unused CSS
* [x] Cleanup story
  * Refactor postgres with postgresDollar
* [x] Remove `case 'object': return 'test-backup';`
* [x] I think the `number-align` class in `_renderSmallItems` and mode is useless
* [x] Add some space on the right of the feature-value in small mode (expanded)

**Comment by Galimede** [comment]
+ : 
- [ ] Fix and investigate why the component isn't going in responsive mode when it's a child of another component

**Comment by hsablonniere** [comment]
TODO:

* [ ] Use up/down instead of chevron-down
* [ ] Fix memory, max size and other features, they don't use bytes (G instead of GB)
* [ ] Merge everything in the init commit
* [ ] Don't use camel case in translations
* [ ] The "microservice" column is weird, how could we merge with with CPU?
* [ ] Fixup comments and TODOs
* [ ] Small refactor here and there
* [ ] We may need more space on the right
