### ISSUE TITLE
Implement cc-pricing-header

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#208]
- [x] Select with shoelace component
- [x] Remove Shadow
- [x] try to adatp the width of the selects (smaller currency, larger zone)
- [x] implement responsive mode
- [x] adapt cc-zone (with custom properties) so it can be highlighted when used in sl-select
- [x] use the prefix/suffix (see jsbin) to have text label + rich HTML in select
- [x] start discussion (issue or discord) with Shoelace about rich select
- [x] investigate the "cost" of adding shoelace
  - [x] run CDN build and analyze the `visualizer-stats-*.html` (add screenshot in this thread)
  - [x] test with some example.html to use pricing-header with local version of CDN (add screenshot devtools network in this thread)
- [x] refactor + cleanup + docs
- [x] CSS
- [x] apply checklist

**Comment by Galimede** [comment]
Visualiser stats file: 
![image](https://user-images.githubusercontent.com/32012475/126293497-fa22ffa2-f764-426c-a224-811c0269f042.png)

Test in network tab: 
![image](https://user-images.githubusercontent.com/32012475/126293552-c7c7b758-1bc9-4de6-a5df-1f190ad0b3f7.png)

**Comment by hsablonniere** [comment]
@Galimede Don't you think the component is a bit huge compared to the others? We'll have to investigate a bit I think...

**Comment by Galimede** [comment]
The component has a weight of :
* 12.3k rendered
* 3.63k gzip
* 3.05k brotli

As a comparison, `cc-pricing-table` is : 
* 10.35k rendered
* 3.04k gzip
* 2.57k brotli

So it's not that much heavier than the others. You might think it's heavier due to its size on the screenshot but I just clicked on it to make it more visible, it doesn't represent its size.  :wink:

**Comment by hsablonniere** [comment]
> So, it's not that much heavier than the others. You might think it's heavier due to its size on the screenshot, but I just clicked on it to make it more visible. It doesn't represent its size. wink

aaaaahhhh
