### ISSUE TITLE
Register the namespace "cc"

### ISSUE THREAD

**Issue by nuxodin** [CleverCloud/clever-components#212]
Maybe you want to register the namespace "cc" here with a pull request?
https://github.com/nuxodin/web-namespace-registry

**Comment by hsablonniere** [comment]
Hello Tobias, I took a quick look at your project but I'm not sure I understand the goal.

**Comment by nuxodin** [comment]
Hi Hubert
Thanks for having a look.
The point is that if others are planning to develop a webcomponents framework, they can look to see if there might be a conflict with another framework.

**Comment by nuxodin** [comment]
I added it.
