### ISSUE TITLE
Modernizing code with safari 14.1 release

### ISSUE THREAD

**Issue by Galimede** [CleverCloud/clever-components#217]
* [x] Replace `||` with Nullish coalescing operator (`??`)
* [x] Use optional chaining operator
* [x] Drop `resize-observer-polyfill`
* [x] Drop `clipboard-copy`
* [x] Why not https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules
* [x] Write a doc about the browser support of the project

**Comment by hsablonniere** [comment]
I looked at our console visit. Safari 14 and 14.1 is a good target. If clients need more, they will need to transpile.

Here's a list of stuff that arrived in Safari 14:

* Added support for the BigInt data type.
* Added support for creating custom instances of EventTarget.
* Added logical assignment operator support.
* Added public class fields support.
  * Warning, with Lit, you cannot init fields with this
  * Added :is() pseudo-selector support as a synonym for :matches().
  * Added :where() pseudo-selector support for specificity adjustment.

Here's a list of stuffs that arrived in Safari 13.1:

* Added support for the nullish coalescing operator ??.
* Added support for the String.prototype.replaceAll method.
* Added support for Resize Observer.
* Added support for the Async Clipboard API.
* Added support for CSS Shadow Parts.
* Added support for the line-break: anywhere; property value.
* Added support for one-finger accelerated scrolling to all frames and overflow:scroll elements eliminating the need to set-webkit-overflow-scrolling: touch.
* Added support for CSS conic gradients.
* Added support for the Pointer Events API enabling consistent access to mouse, trackpad, touch, and Apple Pencil events.
* Disabled -webkit-overflow-scrolling: touch on iPad. All frames and scrollable overflow areas now use accelerated one-finger scrolling without changing stacking.
