### ISSUE TITLE
cc-input-number: disable buttons when necessary

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#229]
We need to set `disabled` on the minus/plus buttons:

* `disabled` => both buttons are visible and disabled
* `readonly`  => both buttons are visible and disabled
* `value` === `min` => minus button is disabled
* `value` === `max` => plus button is disabled

We should style these disabled state with some kind of `opacity: 0.25`.

**Comment by Galimede** [comment]
I have made the buttons visible when in the controls mode and disabled. 
Here is how it looks with a 0.25 opacity :
![image](https://user-images.githubusercontent.com/32012475/114026607-b7137280-9876-11eb-97f9-e51d494de31f.png)
However, I have seen that when the input is in a disabled state it has an opacity of 0.75 which looks like this with the same opacity for the control buttons : 
![image](https://user-images.githubusercontent.com/32012475/114026829-0063c200-9877-11eb-9793-25f844e6c405.png)
I have also tried with 0.5 : 
![image](https://user-images.githubusercontent.com/32012475/114027102-533d7980-9877-11eb-96db-9bfa1efc61fa.png)

IMHO the 0.5 option or the 0.75 would fit better, WDYT @hsablonniere ?

**Comment by hsablonniere** [comment]
@Galimede 0.5 I would say
