### ISSUE TITLE
Required Nodejs version is 14 but lockfile has been generated by npm 7, available with Node >= 15

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-components#273]
Required version in `package.json` and `.npmrc` is `14.x` but the lockfile is in version `2`, which means it has been generated using `npm 7` which comes with `node >= 15`. 

Should this requirement be updated?

**Comment by hsablonniere** [comment]
Yep, you're right. It's just that it's easy with Volta to fix the npm version.
I think Node 16.x should be fine.
We can update the `.nvmrc` and `package.json` for this...

**Comment by hsablonniere** [comment]
Fixed :tada: 

I updated the volta pin and the nvmrc
