### ISSUE TITLE
Improve type definitions

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#275]
Right now we're using TypeScript interface in Markdown code blocks in JSDoc.

* this is very manual
* lots of copy/paste
* VSCode and Webstorm can't use this

We need to create a commond `types.d.ts` and find a way to reference it.

**Comment by hsablonniere** [comment]
An experiment was started in https://github.com/CleverCloud/clever-components/compare/types-jsdoc

**Comment by Galimede** [comment]
* https://custom-elements-manifest.open-wc.org/analyzer/plugins/intro/
* https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html
* https://astexplorer.net/ (Don't forget to use typescript parser)

Also, we have decided to put `@typedef` imports of types in the jsdoc of the class.
