### ISSUE TITLE
cc-pricing-estimation: investigate the vertical alignement of "label: value" in responsive mode

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#283]

**Comment by hsablonniere** [comment]
![Capture d’écran de 2022-03-08 11-30-19](https://user-images.githubusercontent.com/236342/157218708-fc4a69a4-63c9-430e-8b07-aaa6f9ac5ea5.png)

**Comment by florian-sanders-cc** [comment]
Components have been reworked since then and this issue does not apply anymore.
