### ISSUE TITLE
Decide how to implement a pricing-product component for FS Bucket

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#285]
## Context

* At first, having the same component for both Cellar & FS bucket was not seriously considered. FS Bucket only had 1 price interval and no section for traffic.
* Now that we list the "first 100MB are free" as an interval it makes more sense to use the same component for both.

It would look like this for FS Bucket:

![Capture d’écran_2021-07-12_15-47-03](https://user-images.githubusercontent.com/236342/125299689-ab2dc580-e329-11eb-83f8-cb2514dc4600.png)

## Decision

It may be a bit overloaded but the consistency with Cellar is really good so let's go for this.

Now the question is, how do we implement this?

* A component named `<cc-pricing-product-cellar>` was already shipped in `6.10.0`

### A: Deprecate `<cc-pricing-product-cellar>` and create a generic `<cc-pricing-product-storage>`

* It's very sad to deprecate something that was just released but it may be the best solution
* We would need to expose the `icon` and `name`
  * Those would be filled by the smart definition
* We could rely on `intervals.traffic` being an empty array or null to hide it
* FYI: The translated error message contains the word "cellar", could be replaced with something more generic
* We could have a cellar story and a FS bucket story
* I don't think we need 2 smart definition, we could have just one that knows about Cellar and FS Bucket

### B: Create a `<cc-pricing-product-fsbucket>` and move common logic to a generic component

* Exposing two components (both relying on 1 shared generic component) would involve a lot of copy paste (code, translation and stories)
* We would not have to deprecate the cellar component (it has not been used by our own apps yet)

---

Option A it is I guess :tada:

**Comment by Galimede** [comment]
Option A is great, there shouldn't be any problems for `<cc-pricing-page>` to handle it.
If for the event the name is changed, and storage is only sent without traffic for fsbucket I think that shouldn't be a problem.

**Comment by hsablonniere** [comment]
OK, I'll handle it then :wink:
