### ISSUE TITLE
Update cc-pricing-storage for pulsar

### ISSUE THREAD

**Issue by Galimede** [CleverCloud/clever-components#289]
## Context

As a request from yesterday we will have to make a product for pulsar. 
Because its pricing contains intervals and storage, we could use the new `cc-pricing-product-storage` to do this although it might need some tweaks.
Moreover, the pulsar product needs to be shown as its on beta so we may have to include `cc-beta`.

**Comment by hsablonniere** [comment]
* We can start with a story
* What kind of tweaks?
* We often let the user wrap the component with a `<cc-beta>` (we don't embed it in components)

**Comment by hsablonniere** [comment]
Seems like we'll need a new section for inbound traffic.

**Comment by hsablonniere** [comment]
Decision: `intervals` is now an array objects with `type` (storage, inbound traffic...) and `value`

**Comment by hsablonniere** [comment]
Fixed by #300
