### ISSUE TITLE
New pricing component for heptapod

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#301]
@cnivolle can you give us what you need?

**Comment by cnivolle** [comment]
The [Heptapod pricing](https://about.heptapod.host/pricing.html) is based on 5 dimensions:

* active users ("Activity" is any project with merge requests, issues, comments, …) 
* public repositories 
* private repositories 
* storage of repositories
* outgoing traffic 

### User-based billing
* 7€/month **per user active** on any number of **private** repositories
* 7€/month **per 100 users active** only on **public** repositories

### Resource-Based Billing

* 0.02€/month for 1GB of **storage** after 1GB threshold
* 0.09€/month for 1GB of **outgoing traffic** after 100GB threshold

**Comment by hsablonniere** [comment]
The cc-pricing-product-storage could work for this.

* We need to rename it ASAP (more generic name)
* It would require new types of section for users
* The input-number + unit toggle must be a simple input-number for users
* The `PricingStorageSimulator` knows it handles bytes and prices in gigabytes
  * We need to add some kind of `priceFactor` to be more generic

**Comment by hsablonniere** [comment]
@cnivolle seems like there's a 50% discount rule, can we let this aside?

**Comment by cnivolle** [comment]
Yes, we can.
