### ISSUE TITLE
Smart CDN: Allow permissive version 

### ISSUE THREAD

**Issue by Galimede** [CleverCloud/clever-components#304]
As mentioned by @gaelreyrol on Slack, if we want to have the minor changes of a version on the CDN, we currently need to be specific about the version that contains the last minor changes. We can't just stay on the same base version and get the changes without specifying it otherwise we will get a 500 error.

Could we make this possible so that we could put the base version once and get all the minor changes? 

e.g.: I am on the version 7 of the smart CDN and I want the latest fixes who are on the 7.1.2. If I stay on the 7 version, I won't be able to get them and get a 500 error. So, i will have to specify 7.1.2 instead but that does mean I will have to manually fix it every time if there are new fixes and I do want them. 

What we would want is to put only the 7 version once and get all the changes that goes to 7.x.z if we don't specify a specific minor release version.

**Comment by gaelreyrol** [comment]
To add more context, it's working with the version `6`, the smart cdn is loading the latest available version `6.10.0` but not with `7` which should retrieve this version: `7.0.0-beta.0` and returns a 500 error.

- `https://components.clever-cloud.com/load.js?version=6&components=cc-pricing-product.smart-addon` -> OK
- `https://components.clever-cloud.com/load.js?version=7&components=cc-pricing-product.smart-addon` -> KO

Also I don't know if it's related but when I am trying to get a version that does not exists like `8` it also returns a 500 error, I think a 404 error would be better.

**Comment by hsablonniere** [comment]
We don't want prerelease tags to match losse semver ranges.

Example: `7` should not match `7.0.0-beta.0`

We'll fix the 500 bug though in this issue: https://github.com/CleverCloud/clever-components-cdn/issues/1
