### ISSUE TITLE
cc-pricing-product-consumption: Change price system API call to have pulsar BETA prices

### ISSUE THREAD

**Issue by Galimede** [CleverCloud/clever-components#305]
Right now in the `cc-pricing-product-consumption` (smart) when requesting the price system we only ask for a zone_id.
However, when we want to instantiate it to get the pulsar product, the price system does not take into account that we need the price system to the date of the September 1st to get the BETA prices for pulsar specifically. 

I have made a small fix on `test-pulsar` branch but I think we could do better.

**Comment by hsablonniere** [comment]
* We could add a date on the context of the smart components for `<cc-pricing-product-*>`.
* It's not a high priority

**Comment by hsablonniere** [comment]
Closing this for now.
