### ISSUE TITLE
cc-action-dispatcher: init component

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#353]
## Context

We basically want to ping all clever cloud VMs in one click.

On each VM there lives a piece of Rust called `action-dispatcher` that listens on [Pulsar](https://pulsar.apache.org/)
and execute various actions.
One of those actions consists in responding to a `ping` message, with a `pong` obviously.

So we want to create an `action-dispatcher`-managing page on CC Admin (a very private, server-side rendered administration tool).

The architecture of this project looks like this:

```

                    +-----------------------+
                    |                       |
                    |      ccadmin front    |
                    |                       |
                    |                       |
                    +---+-------------------+
                        |             ^
               HTTP     |             | JSON
                        V             |
                    +-----------------+-----+
                    |                       |
                    |      ccadmin back     |        subscribes to
                    |                       +-------------+
                    |                       |             |
            +-------+------+-------------+--+             |
            |              |             |                V
            |              |             |           +-----------+
            |              |             |           |  pulsar   |
  produces  |              |             |           | response  |
     on     |              |             |           |   topic   |
            V              V             V           +-----------+
      +--------+       +--------+     +--v-----+          ^
      |        |       |        |     |        |          |
      | pulsar |       | pulsar |     | pulsar |          |
      | topic  |       | topic  |     | topic  |          |      TOPICS
      | app-id |       | app-id |     | app-id |          |
      +--------+       +--------+     +--------+          |
          ^                 ^               ^             |
subscribe |                 |               |             |
   to     |                 |               |             |
      +---+----+       +----+---+     +-----+--+          |
      |        |       |        |     |        |          |
      | action |       | action |     | action |          |
      | dispa. |       | dispa. |     | dispa. |          |     VIRTUAL MACHINES
      | app-id |       | app-id |     | app-id |          |
      +----+---+       +---+----+     +----+---+          |
           |               |               |              |
           +---------------+---------------+--------------+
                                       produce on...
```

This implies we create a `cc-action-dispatcher` component that allows any administrator to just click a `Ping all machines` button and have a nice list of:

- how many machines were pinged
- how many did not respond (or, rather said, how many `action-dispatcher` entities did not respond)
- the `id`s of unresponsive entities

## Inputs

* state
  * init (default)
  * waiting (just after click on send action)
  * error (error on the first cc-api call)
  * response (after the first cc-api response)
* response
  * pingCount
  * pongCount
  * (errors ??)

## Outputs

* send-action (will contain the name of the action and the parameters)
  * name: ping
  * all | list of IDs

## To be defined

We're still discussing how we would timeout stuffs and consider VM unresponsive.
We may add a abort button and trigger a "X VMs remained silent with the list of IDs".

## Stories

* init
* waiting
* error
* data with X pings
* data with X pings and Y pongs
* data with X pings and Y+N pongs
* simulations

**Comment by Keksoj** [comment]
![Untitled Diagram drawio](https://user-images.githubusercontent.com/29835330/150960396-e7708c3d-0c3e-4f14-acd9-a110bbbcbedd.png)
