### ISSUE TITLE
We need to settle on how we enforce formatting

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#383]
Since the beginning of the project we relied on WebStorm's formatter. With the team growing, we need to find something else.

* https://prettier.io/
* https://dprint.dev/
* https://biomejs.dev/ (Rome's replacement) 
* https://eslint.org/

**Comment by florian-sanders-cc** [comment]
:wave: I played with eslint as a formatter yesterday and finally got it working as a formatter in VSC.
I think it might be our best lead to finding a formatter that fits all our needs considering how much it can be configured.
I'll do more testing later to see if it is possible to implement everything we need.

@hsablonniere could you send me the playground you used for prettier so I don't miss use cases ? :smile:

**Comment by roberttran-cc** [comment]
Full support on this initiative!

[Rome](https://rome.tools/) looks super promising but [language support](https://rome.tools/#language-support) may lack at the moment...

Regardless of the tool, I guess we could quickly handle the usual suspects:
- indent style (`tab` or `space`),
- indent size (`2`, `4` or something else),
- EOL break (`lf`, `cr` or `crlf`),
- charset,
- trimming trailing white-space,
- file ends with newline or not.

**Comment by florian-sanders-cc** [comment]
Update: 
It looks like `dprint` is used by the [Typescript team](https://github.com/microsoft/TypeScript).
It probably means it got decent support and it's going to keep being maintained?

It might be worth checking if it meets our needs.

**Comment by florian-sanders-cc** [comment]
Update: 
Rome project seems to be dead but there is an active fork named Biome.
- Docs: https://biomejs.dev/
- GitHub: https://github.com/biomejs/biome
I'll update the issue description :+1:

**Comment by florian-sanders-cc** [comment]
Closing the issue since we're now using Prettier thanks to @Galimede awesome work :muscle: 
See #1030 & [ADR #26](https://www.clever-cloud.com/doc/clever-components/?path=/docs/%F0%9F%93%8C-architecture-decision-records-adr-0026-introducing-prettier-as-a-formatter--docs) for more info :wink:
