### ISSUE TITLE
cc-pricing-page: the zone input in the header is stuck in blinking animation on Safari

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#394]
https://user-images.githubusercontent.com/236342/158354050-7453bed2-6956-48a4-9ed0-a096ee03f08d.mov

**Comment by Galimede** [comment]
Observations:

* There is an error recurring on safari on the pricing components related to the resize observer (I do think it is more related to components that implement it but this need further investigation) -> `ResizeObserver loop completed with undelivered notifications.` (It does not seem to be the cause of the bug though)
* When checking `cc-pricing-header` on the production SB everything seems fine
* Same on `cc-pricing-page` **except**  when checking the  _smart_  version where the blinking/skeleton gets triggered until you go to another component and go back to the smart story. 
...
