### ISSUE TITLE
cc-payment-warning: init component

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#402]
## Context

We need a component to display warnings when some payment method are not "valid".
We have 3 types of payment method error:

* no payment method
* no default payment method
* default payment method is expired

The clever-client handles this...

We need 3 variants of this component:

* one for `home` with links to payment pages of orgas with errors
* one for the `orga-overview` with link to payment page
* one for the `orga-billing`

The user of the component cannot use it if there are no errors.

## Input

* mode: `"home" | "overview" | "billing"`
* errors: `Array<{ type: number, orgaName: string, orgaBillingLink: string }>`

## Output

none

## Stories

* mode home, one error (one instance for each error type)
* mode home, multiple errors (all 3 types)
* mode overview (one instance for each error type)
* mode billing (one instance for each error type)

**Comment by florian-sanders-cc** [comment]
@hsablonniere background color variable to add inside defaultThemeStyle:
# Choices
`--cc-color-orange-light: #fff9cb;`
`--cc-color-yellow: #e9e138;`

# Decisions
## background region
`--cc-color-bg-warning-light: var(--cc-color-orange-light);` 

## border region
`--cc-color-border-warning: var(--cc-color-yellow);`
