### ISSUE TITLE
cc-article-card: init component

### ISSUE THREAD

**Issue by Galimede** [CleverCloud/clever-components#406]
## Context

We need a component to display a card that contains basic information about an external article with a button that redirects to this article. It should contains: a title, a short description, the date of the article, a link (hat looks like a button) that redirects to the external article and a banner image.

# Data 

We'll need both RSS in French and English:
* https://www.clever-cloud.com/fr/feed/
* https://www.clever-cloud.com/feed/

## Input

* title: string
* content: string
* date: string?
* banner: string (link to the image)
* link: string

## Output

none

## Stories

* Default
* Error
* Loading (waiting for data)

**Comment by hsablonniere** [comment]
First feedbacks:

This is awesome :tada:

* you don't need the error story, I think we'll display one error message for the whole list of article cards
* you don't need the waiting story, it's useful when the component as server interactions (API calls)
* you don't need the empty story
* we need something else that the "link"
  * we can rename it in "read the article" (with a more detailed title)
  * we can also just remove this link and make the title a link
* the sizing/positionning of the image is broken

**Comment by hsablonniere** [comment]
Last detail:

Can you move the description fake string to a span inside the div and move the skeleton class to the span. This way you'll move from this:

![Capture d’écran de 2022-03-25 11-38-10](https://user-images.githubusercontent.com/236342/160105598-b1d58ce4-b80d-489c-adcc-ecd40211986c.png)

to this:

![Capture d’écran de 2022-03-25 11-38-04](https://user-images.githubusercontent.com/236342/160105628-b8f309a6-7195-433f-b5d4-cb9a97cb51f7.png)
