### ISSUE TITLE
Move "Release" and "Contributing" to the "Docs" section instead of home

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#425]
I was surprised not to find "Release" in the "Docs" section and without @Galimede I would not have seen it in the "Home" section.

Should we move "Release" and "Contributing" sections in the "Docs" instead of "Home" or is this a bad idea ?
![image](https://user-images.githubusercontent.com/100240294/163409739-351eec9e-9393-4a7a-97e5-ef7d04d7e391.png)

**Comment by Galimede** [comment]
Personally I didn't remember that `Releases` was the docs to know how to release. 
If we move both `Contributing` and `Releases `, I do think we should rename them to something like: 
* How to contribute? 
* How to release the components?

As for its current state, you could think that for `Releases` you would see the `CHANGELOG` and not the document to know how to release.
That is kind of confusing imo.

**Comment by hsablonniere** [comment]
Agreed, let's do this:

1. Move them to the docs part (change the `kind` in the front matter)
2. Rename titles

* How to contribute?
* How to release the components?
