### ISSUE TITLE
Discussion: our test framework

### ISSUE THREAD

**Issue by Galimede** [CleverCloud/clever-components#485]
## Context 

We use web test runner from modern web to test things on our component library. It is great and does its job but it becomes quite complicated when you want to test methods that are not Node.js related. Indeed, the test runner does run in a browser so you can't access Node.js methods here. 

For example, in order to test our cem types plugin we do need typescript which we can't use with test runner because it does need Node.js.

The question is: Do we need and want another test framework for these and future specific use cases?

**Comment by Galimede** [comment]
We have discussed this question internally and we have chosen the solution to add **Mocha** as an addition to our already present web test runner to be able to test things that require Node.js. 

## Why Mocha?

We have chosen Mocha over other frameworks like Jest because it's pretty lightweight (177.6 kB minified) and a big part of the team is already familiar with it. It also allows us to use the same syntax and stick with Chai for the assertion.
The only downside is for a question of module we need to have two instances of them `Chai` for Mocha and `@bundled-es-modules/chai` for web test runner.

## Why not stick with web test runner only?

As already mentioned previously, web test runner does run in a browser which does not allow us to use native Node.js modules like `fs` for example.

**Comment by hsablonniere** [comment]
@Galimede I guess we can close this, what do you think?
