### ISSUE TITLE
cc-addon-admin: skeleton story seems to be broken

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#496]
The [`<cc-addon-admin>` skeleton story](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-addon-cc-addon-admin--skeleton) is supposed to show skeleton text inputs but it seems to be broken.

Haven't had time to check exactly why.

**Comment by hsablonniere** [comment]
I think it's because the private `_skeleton` has a default to `false.
Maybe we could stop using the `addon` setter and use the `update` lifecycle callback instead.
