### ISSUE TITLE
cc-env-var-form: the reset button is broken

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#497]

**Comment by roberttran-cc** [comment]
Looks like a side effect from https://github.com/CleverCloud/clever-components/commit/dd533927ca54a614cf09e44ee3786ed066116faa.

Investigating [form reset](https://github.com/CleverCloud/clever-components/blob/master/src/env-var/cc-env-var-form.js#L177) that does not trigger [model update](https://github.com/CleverCloud/clever-components/blob/master/src/env-var/cc-env-var-form.js#L194) which effectively [reset](https://github.com/CleverCloud/clever-components/blob/master/src/env-var/cc-env-var-form.js#L219) the datas.
