### ISSUE TITLE
cc-article-list extensions

### ISSUE THREAD

**Issue by rajeevb2** [CleverCloud/clever-components#639]
I want to add two custom fields that show up on the article card. How do I do this?

Also, I would like a scrollbar incase there are too many cards

**Comment by hsablonniere** [comment]
Hello @rajeevb2, I'm not sure I understand your question. Our project is mostly intended to be used by our products for now. I would advise you to have a look at shoelace.style/, it's very well done and designed to be reused in any project by anyone.
