### ISSUE TITLE
cc-button:click event handler for two buttons

### ISSUE THREAD

**Issue by rajeevb2** [CleverCloud/clever-components#659]
I had two cc-button buttons with different id tags in the same for form. Since you can have only 1 cc-button:click handler, I was using event.target.id to determine the button pressed. This works in backlight.dev but fails in a javascript file. Is there something else that is better

**Comment by hsablonniere** [comment]
Hello @rajeevb2, I'm not sure I understand your question. Our project is mostly intended to be used by our products for now. I would advise you to have a look at shoelace.style/, it's very well done and designed to be reused in any project by anyone.
