### ISSUE TITLE
Missing entries into package.json

### ISSUE THREAD

**Issue by antleblanc** [CleverCloud/clever-components#70]
Hi!

I noticed after a first installation, that npm reports two warnings.

```sh
npm WARN @clevercloud/components@1.3.0 No repository field.
npm WARN @clevercloud/components@1.3.0 No license field.
```

Both `repository` and `license` entry are missing from the `package.json` file.

Resources:
- https://docs.npmjs.com/files/package.json#repository
- https://docs.npmjs.com/files/package.json#license

Feel free to tell me if you want me to open the corresponding  Pull Request.
But in order to do that I need you to add the corresponding `LICENSE` file.

Thanks!

**Comment by hsablonniere** [comment]
Yep, we're sill discussing the license, we procrastinated, we need to settle on this.

**Comment by hsablonniere** [comment]
Fixed ;-)
