### ISSUE TITLE
test: work around ResizeObserver loop limit exceeded errors

### ISSUE THREAD

**Issue by pdesoyres-cc** [CleverCloud/clever-components#761]
During unit tests, we can see a lot of `ResizeObserver loop limit exceeded` errors.

We could get inspiration from https://github.com/lit/lit/pull/3929

We may also want to filter those errors in Glitchtip.

**Comment by hsablonniere** [comment]
@pdesoyres-cc Thanks for your issue, I read virtualizer issue and it helped me a lot. I took some time to dig the subject and created another issue with the details, the solutions and a proposition. Let's continue the discussion there.

https://github.com/CleverCloud/clever-components/issues/808
