### ISSUE TITLE
cc-pricing: add new feature translations

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#804]
## Context

On the Website, we may want to display new features that currently have no translations.

@cnivolle could you provide the texts and translations you need?

In our last meeting we identified the following features that have no translations yet and that we'd like to display:

- code: `is-migratable`:
  - translation fr: ?
  - translation en: ?
- code: `dedicated`:
  - translation fr: ?
  - translation en: ?

**Comment by cnivolle** [comment]
* code: `is-migratable`:
  * translation fr: Outil de migration
  * translation en: Migration tool
* code: `dedicated`:
  * translation fr: Dédié
  * translation en: Dedicated

**Comment by florian-sanders-cc** [comment]
reopening the issue just so we don't forget to actually add these translations in the components. 

Thanks for your input @cnivolle :wink:
