### ISSUE TITLE
transform empty state message into a cc-notice with an info intent

### ISSUE THREAD

**Issue by Galimede** [CleverCloud/clever-components#805]
With the soon arrival of #645 we thought that we may replace our empty state message in our components with a `cc-notice` with an `info` intent.
We'll need to discuss if we want to do that or not though.

## Components impacted

- [ ] cc-addon-backups
- [ ] cc-adon-linked-apps
- [ ] cc-env-var-editor-simple
- [ ] cc-env-var-form
- [ ] cc-env-var-linked-services
- [ ] cc-invoice-list
- [ ] cc-ssh-key-list
- [ ] cc-tcp-redirection-form
- [ ] cc-tile-deployments
- [ ] cc-tile-instances
- [ ] cc-tile-metrics
- [ ] cc-tile-requests
- [ ] cc-tile-status-codes

// TODO

**Comment by hsablonniere** [comment]
I think it's a nice idea, what about you @CleverCloud/frontend-team ?

**Comment by florian-sanders-cc** [comment]
:wave: I'm not sure, I like that empty messages are very subtle at the moment.

But maybe there are cases where I would agree with you, Do you have some examples in mind?

**Comment by pdesoyres-cc** [comment]
I would be in favour of that

**Comment by hsablonniere** [comment]
Maybe it doesn't work for all our "empty" stories.

![image](https://github.com/CleverCloud/clever-components/assets/236342/9656aac2-0352-4c13-9243-6121aeb166d1)

**Comment by florian-sanders-cc** [comment]
It's definitely worth testing and discussing cases where we're not sure it works like we did for error states :+1:
