### ISSUE TITLE
cc-icons: tree shaking issue with the CDN build

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#898]
## Context

Components that rely on the `cc-icon` seem to trigger the fetch of all icons instead of just the ones they are using.

In the CDN bundle, it looks like all icons are regrouped within a `cc-remix.icons.hash.js` file. 

We need to investigate and find a solution so that components only fetch icons they need.

**Comment by hsablonniere** [comment]
This comes from this line: https://github.com/CleverCloud/clever-components/blob/master/rollup/rollup-common.js#L80

With this config, the CDN build will consider icon files as entrypoints and:

* won't tree shake
* won't split/inline the imports

I don't remember if we really want the icons to be published to npm as a "main" file but for the CDN build, we don't need these icon files to be entry points.
