### ISSUE TITLE
cc-env-var-form: behaviour when switching between modes

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#94]
Let's assume the following state in simple mode:

* `ONE` => `1`
* `TWO` => `2`
* `THREE` => `3`

In this simple mode, you are prevented from adding a variable named `THREE` a second time and it's good.

If you switch to expert mode: 

```
ONE="1"
THREE="3"
TWO="2"
```

you be able to change the some values but also to type `THREE` a second time:

```
ONE="11"
THREE="3"
TWO="22"
THREE="333"
```

In this case, an error will be displayed:

```
line 4: be careful, the name THREE is already defined
```

If you switch back to simple mode, you can see that nothing has changed, even `ONE="11"` or `TWO="22"` are not changed.

QUESTION 1: Should we keep this behaviour?

QUESTION 2: Should we prevent the user from switching modes if there is an error?

If you switch again from simple mode to expert mode, you will still see this:

```
ONE="11"
THREE="3"
TWO="22"
THREE="333"
```

You won't see the error message :-(

QUESTION 3: Should we display back the error message? => YES!

If you switch to simple, edit `ONE` to `111` and go back to expert mode, you will see this:

```
ONE="11"
THREE="3"
TWO="2"
```

The previous entry is lost.

QUESTION 4: Is this what we want?

**Comment by Galimede** [comment]
What about keeping only what is valid when switch modes ?

**Comment by Galimede** [comment]
FYI: Errors in expert mode dissapear when switching to simple and switching back to expert.

**Comment by Galimede** [comment]
We decided with @hsablonniere to keep only valid variables when switching between modes.
