### ISSUE TITLE
Investigate CEM Analyzer & TypeScript update opportunity

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#950]
## Context

The `typescript` package version used in our dev dependencies is tied to the version bundled by the `CEM Analyzer` package on purpose.

We use it mainly for two things : 

- tests related to the docs (generated by the CEM Analyzer),
- typechecking within our IDEs.

This is why we use the same version as CEM Analyzer, we want the types to be the same in our docs, our tests on these docs & our typechecking tools.

The `typescript` version currencly in use in our project is `4.3.5`. It is ~2 years old and several tools are no longer supporting it (`ts-lit-plugin`, `lit-analyzer`, `commitlint`). 

For some of them, this is not a problem because they bring it in their dependencies (`commitlint`).
But `ts-lit-plugin` & `lit-analyzer` both rely on the local typescript version found within the project.

It looks like `CEM Analyzer` released a few versions in which they have upgraded typescript. We should try and upgrade these packages.

We'll have to check very carefully that our docs do not break. :monocle_face:

**Comment by Galimede** [comment]
fyi, tested upgrading cem to the latest version and changing the TS version accordingly, it doesn't break anything.
I still wonder though if we shouldn't separate our cem plugin from our repo to put it somewhere else to bring whatever TS version we'd like.
