### ISSUE TITLE
Add a JSON mode to `<cc-env-var-form>`

### ISSUE THREAD

**Issue by hsablonniere** [CleverCloud/clever-components#97]
* [ ] Extract JSON validation from the CLI https://github.com/CleverCloud/clever-tools/pull/409 and move it to the client https://github.com/CleverCloud/clever-client.js/issues/28
* [x] Create a `<cc-env-var-editor-json>`
* [x] Use `<cc-env-var-editor-json>` in `<cc-env-var-form>`

**Comment by Galimede** [comment]
- Delete simple quote from placeholder
- Should we make an empty array when there's no env vars
